import torch
import torch.nn as nn
from .encoder import TransformerBlock

class LatentPredictor(nn.Module):
    def __init__(self, embed_dim=192):
        super().__init__()
        self.predictor_block = TransformerBlock(embed_dim)
        
    def forward(self, context_tokens, target_masks_tokens):
        # Combines unmasked visual elements with raw positional placeholders
        combined_flow = context_tokens + target_masks_tokens
        return self.predictor_block(combined_flow)

class DensePredictorLoss(nn.Module):
    def __init__(self, lambda_context=0.5):
        super().__init__()
        self.lambda_context = lambda_context
        self.mse = nn.MSELoss()

    def forward(self, predicted_embeddings, target_embeddings, mask_indices):
        """
        Args:
            predicted_embeddings: Outputs produced by the predictor block [B, N, D]
            target_embeddings: Ground truth target features generated by target encoder [B, N, D]
            mask_indices: Binary tensor map pointing to targeted mask sectors [B, N]
        """
        # Convert mask flags into inversion formats for clean matrix mapping
        inverted_mask = 1.0 - mask_indices 
        
        # Component 1: Loss on masked zones (standard JEPA strategy)
        masked_loss = self.mse(predicted_embeddings * mask_indices.unsqueeze(-1), 
                               target_embeddings * mask_indices.unsqueeze(-1))
        
        # Component 2: Dense contextual grounding calculation (V-JEPA 2.1 upgrade)
        context_loss = self.mse(predicted_embeddings * inverted_mask.unsqueeze(-1), 
                                target_embeddings * inverted_mask.unsqueeze(-1))
        
        total_dense_loss = masked_loss + (self.lambda_context * context_loss)
        return total_dense_loss, masked_loss, context_loss